### ISSUE TITLE
Packages not actually loading in emacs-live

### ISSUE THREAD

**Issue by neverfox** [ardumont/emacs-live-packs#5]
As I further attempt to get this working with emacs-live using the new conventions, I noticed that, while I don't get any errors, the packs don't seem to be actually loading, as none of the defined functions are available, package repositories aren't brought online (e.g. Melpa) etc.

```
==> Loading Emacs Live Pack: ~/.emacs-live-packs/install-packages-pack/


==> Loading Emacs Live Pack: ~/.emacs-live-packs/buffer-pack/


==> Loading Emacs Live Pack: ~/.emacs-live-packs/scratch-pack/


==> Loading Emacs Live Pack: ~/.emacs-live-packs/lisp-pack/


==> Loading Emacs Live Pack: ~/.emacs-live-packs/git-pack/


==> Loading Emacs Live Pack: ~/.emacs-live-packs/shell-pack/


==> Loading Emacs Live Pack: ~/.emacs-live-packs/clojure-pack/


==> Loading Emacs Live Pack: ~/.emacs-live-packs/clojurescript-pack/


==> Loading Emacs Live Pack: ~/.emacs-live-packs/modeline-pack/


==> Loading Emacs Live Pack: ~/.emacs-live-packs/elisp-pack/


 Pack loading completed. Your Emacs is Live...
```

Example:
`M-x goto-line-with-feedback [No match]`

**Comment by ardumont** [comment]
Hello,

Sorry for the delay.
I was not aware of this issue (I somehow `unwatched` my repository).

You are right about the loading. It changed and I forgot that now, we need to `require` the package explicitely (I will update this).

For the message part, it's just no longer displaying the metadata (some packs no longer have them).

Working on it.

Cheers,

**Comment by neverfox** [comment]
Thanks!

**Comment by ardumont** [comment]
I have not forgotten.
Just having hard time organizing myself...

**Comment by neverfox** [comment]
Thanks for the update. Looking forward to it.

**Comment by ardumont** [comment]
> Thanks for the update. Looking forward to it.

So I'm trying to unify emacs-live-packs and prelude-packs's loading.
I'm almost there...

But, I hit a glitch regarding package initialization in emacs-live env.
I'm all down to the mandatory passage of `(package-initialize)`.
In the stack trace call, it requires the `info` module and fails (it does not found it).

Even though the load-path is ok and list a folder containing it.
That's the issue!

Anyway, can you please try this in your buffer?

Copy this inside a scratch buffer:
```lisp
(require 'info)
```
<kbd>M-x eval-buffer RET</kbd>

What does this tell you?

On my emacs-live, it fails.
But forcing emacs to load it accordingly:

```lisp
(require 'info "/nix/store/pn3j6m7smaswwigmm7194cp1wfgc0glr-emacs-24.5/share/emacs/24.5/lisp/info")
```

And now reloading emacs-live, it's better.

Thanks for your feedback on this.

Cheers,

**Comment by ardumont** [comment]
Yes! Thanks for listening!

It boils down to the load-path... again!
The `info` mode was not found but a `info.el` was.
This one not `provid`ing the info expected, thus failing!

Thanks to this snippet, I had the `eureka` moment:
```lisp
(locate-library "info")
```
This listed me the `info.el` file present in the `emacs-live-packs/prelude-live-pack`.
Which is clearly not the right one.

So my error was to push new element (mode) in the load-path before the native ones.
Appending them is the right approach.

Cheers,

**Comment by ardumont** [comment]
So, I pushed the fix.

Cheers,

**Comment by neverfox** [comment]
Still no go. When I run `(require 'info)` in `*scratch*`, I get ``Required feature `info' was not provided`` None of the additional package repos are added (which is my check that `install-packages-pack` has loaded. If there's a better check that the packs are loading, what would that be?

**Comment by ardumont** [comment]
> Still no go. When I run (require 'info) in *scratch*, I get Required feature `info' was not provided.

- How do you update the emacs-live-packs repository?
- What does this give you?

```lisp
(locate-library "info")
```

> None of the additional package repos are added (which is my check that install-packages-pack has loaded. 

Yes, I do the same.
<kbd>M-g g</kbd>.

> If there's a better check that the packs are loading, what would that be?

I guess this should do it:
```lisp
(locate-library "install-packages-pack")
```

Cheers,

**Comment by neverfox** [comment]
> How do you update the emacs-live-packs repository?

For good measure, I made a fresh clone --recursive

> What does this give you?

`/Users/neverfox/.emacs.d/packs/stable/bindings-pack/info.el`

> M-g g

I get `Goto line:` in the minibuffer.

> (locate-library "install-packages-pack")

`/Users/neverfox/.emacs-live-packs/install-packages-pack/install-packages-pack.el`

**Comment by ardumont** [comment]
> > What does this give you?

> /Users/neverfox/.emacs.d/packs/stable/bindings-pack/info.el

Ok.
According to my actual understanding, this is where the trouble is.
But here we are inside emacs-live's startup...

This should give something more like:
```lisp
"/usr/share/emacs/24.5/lisp/info.elc"
```
Your mileage may vary (please adapt according to your machine).

For my part, running debian with nix package installer, it's:
```lisp
"/nix/store/pn3j6m7smaswwigmm7194cp1wfgc0glr-emacs-24.5/share/emacs/24.5/lisp/info.elc"
```

Can you please try to add this at the beginning of your `~/.emacs-live.el`?

```lisp
(add-to-list 'load-path "/usr/share/emacs/24.5/lisp/")
```

The goal is to make this folder more important than emacs-live's (or emacs-live-packs) ones.
Indeed, `package.el` is more like an emacs primitive folder than any other.

Cheers,

**Comment by neverfox** [comment]
Still returns `/Users/neverfox/.emacs.d/packs/stable/bindings-pack/info.el`

**Comment by ardumont** [comment]
Ok.

> For good measure, I made a fresh clone --recursive

I did not answer but this is good :D by the way.

> >  M-g g

> I get Goto line: in the minibuffer, which is what I get in vanilla emacs-live.

Yes, what I meant is that I check the same as you.
Only on my side, I do see the numbering mode which is activated.

> Still returns /Users/neverfox/.emacs.d/packs/stable/bindings-pack/info.el

Can you please show me your actual load-path?

<kbd>M-x ielm RET load-path RET</kbd>

This will open an emacs-lisp repl which will display the complete content of your load-path.

Here is mine:
```lisp
("/home/tony/.emacs.d/packs/stable/bindings-pack/lib/" "/home/tony/.emacs.d/packs/stable/clojure-pack/lib/eval-sexp-fu" "/home/tony/.emacs.d/packs/stable/clojure-pack/lib/ac-nrepl" "/home/tony/.emacs.d/packs/stable/clojure-pack/lib/cider" "/home/tony/.emacs.d/packs/stable/clojure-pack/lib/clj-refactor" "/home/tony/.emacs.d/packs/stable/clojure-pack/lib/align-cljlet" "/home/tony/.emacs.d/packs/stable/clojure-pack/lib/clojure-mode" "/home/tony/.emacs.d/packs/stable/clojure-pack/lib/auto-complete" "/home/tony/.emacs.d/packs/stable/clojure-pack/lib/popup-el" "/home/tony/.emacs.d/packs/stable/clojure-pack/lib/fuzzy-el" "/home/tony/.emacs.d/packs/stable/clojure-pack/lib/uuid" "/home/tony/.emacs.d/packs/stable/clojure-pack/lib/" "/home/tony/.emacs.d/packs/stable/org-pack/lib/org-mode/contrib/lisp" "/home/tony/.emacs.d/packs/stable/org-pack/lib/org-mode/lisp" "/home/tony/.emacs.d/packs/stable/org-pack/lib/" "/home/tony/.emacs.d/packs/stable/git-pack/lib/magit" "/home/tony/.emacs.d/packs/stable/git-pack/lib/git-modes" "/home/tony/.emacs.d/packs/stable/git-pack/lib/" "/home/tony/.emacs.d/packs/stable/power-pack/lib/wc-mode" "/home/tony/.emacs.d/packs/stable/power-pack/lib/floobits/" "/home/tony/.emacs.d/packs/stable/power-pack/lib/floobits" "/home/tony/.emacs.d/packs/stable/power-pack/lib/emacs-git-gutter" "/home/tony/.emacs.d/packs/stable/power-pack/lib/multiple-cursors" "/home/tony/.emacs.d/packs/stable/power-pack/lib/ace-jump-mode" "/home/tony/.emacs.d/packs/stable/power-pack/lib/expand-region" "/home/tony/.emacs.d/packs/stable/power-pack/lib/browse-kill-ring" "/home/tony/.emacs.d/packs/stable/power-pack/lib/logito" "/home/tony/.emacs.d/packs/stable/power-pack/lib/pcache" "/home/tony/.emacs.d/packs/stable/power-pack/lib/gh" "/home/tony/.emacs.d/packs/stable/power-pack/lib/gist" "/home/tony/.emacs.d/packs/stable/power-pack/lib/scratch" "/home/tony/.emacs.d/packs/stable/power-pack/lib/refheap" "/home/tony/.emacs.d/packs/stable/power-pack/lib/undo-tree" "/home/tony/.emacs.d/packs/stable/power-pack/lib/yasnippet" "/home/tony/.emacs.d/packs/stable/power-pack/lib/volatile-highlights" "/home/tony/.emacs.d/packs/stable/power-pack/lib/" "/home/tony/.emacs.d/packs/stable/lang-pack/lib/haskell-mode" "/home/tony/.emacs.d/packs/stable/lang-pack/lib/extempore" "/home/tony/.emacs.d/packs/stable/lang-pack/lib/glsl-mode" "/home/tony/.emacs.d/packs/stable/lang-pack/lib/js2" "/home/tony/.emacs.d/packs/stable/lang-pack/lib/actionscript-mode" "/home/tony/.emacs.d/packs/stable/lang-pack/lib/scel" "/home/tony/.emacs.d/packs/stable/lang-pack/lib/ruby-mode" "/home/tony/.emacs.d/packs/stable/lang-pack/lib/yaml-mode" "/home/tony/.emacs.d/packs/stable/lang-pack/lib/" "/home/tony/.emacs.d/packs/stable/colour-pack/lib/live-fontify-hex" "/home/tony/.emacs.d/packs/stable/colour-pack/lib/color-theme" "/home/tony/.emacs.d/packs/stable/colour-pack/lib/" "/home/tony/.emacs.d/packs/stable/foundation-pack/lib/popwin" "/home/tony/.emacs.d/packs/stable/foundation-pack/lib/elisp-slime-nav" "/home/tony/.emacs.d/packs/stable/foundation-pack/lib/ibuffer-git" "/home/tony/.emacs.d/packs/stable/foundation-pack/lib/smex" "/home/tony/.emacs.d/packs/stable/foundation-pack/lib/flx" "/home/tony/.emacs.d/packs/stable/foundation-pack/lib/pkg-info" "/home/tony/.emacs.d/packs/stable/foundation-pack/lib/epl" "/home/tony/.emacs.d/packs/stable/foundation-pack/lib/s" "/home/tony/.emacs.d/packs/stable/foundation-pack/lib/dash" "/home/tony/.emacs.d/packs/stable/foundation-pack/lib/auto-compile" "/home/tony/.emacs.d/packs/stable/foundation-pack/lib/packed" "/home/tony/.emacs.d/packs/stable/foundation-pack/lib/" "/home/tony/.emacs.d/elpa/ac-math-20141116.1327/" "/home/tony/.emacs.d/elpa/ace-jump-mode-20140207.530" "/home/tony/.emacs.d/elpa/aggressive-indent-20150516.238/" "/home/tony/.emacs.d/elpa/async-20150529.529/" "/home/tony/.emacs.d/elpa/auto-complete-1.4" "/home/tony/.emacs.d/elpa/buffer-move-20130923.1653" "/home/tony/.emacs.d/elpa/cider-20140226.716" "/home/tony/.emacs.d/elpa/cljsbuild-mode-0.2.0" "/home/tony/.emacs.d/elpa/clojurescript-mode-0.5" "/home/tony/.emacs.d/elpa/color-theme-20080305.34/" "/home/tony/.emacs.d/elpa/company-20150525.658/" "/home/tony/.emacs.d/elpa/creds-0.0.4" "/home/tony/.emacs.d/elpa/cyberpunk-theme-20131205.1256" "/home/tony/.emacs.d/elpa/deferred-20150309.2052/" "/home/tony/.emacs.d/elpa/dockerfile-mode-20150407.550/" "/home/tony/.emacs.d/elpa/el-mock-20130806.1348" "/home/tony/.emacs.d/elpa/elnode-0.9.9.7.6" "/home/tony/.emacs.d/elpa/creole-1.0.3" "/home/tony/.emacs.d/elpa/emr-20140817.1604/" "/home/tony/.emacs.d/elpa/ert-expectations-20130824.1200" "/home/tony/.emacs.d/elpa/esxml-0.3.0" "/home/tony/.emacs.d/elpa/db-0.0.6" "/home/tony/.emacs.d/elpa/eval-sexp-fu-20131230.1351/" "/home/tony/.emacs.d/elpa/exec-path-from-shell-1.7" "/home/tony/.emacs.d/elpa/expectations-mode-0.0.4" "/home/tony/.emacs.d/elpa/fakir-0.1.8" "/home/tony/.emacs.d/elpa/flymake-shell-0.8" "/home/tony/.emacs.d/elpa/flymake-easy-0.9" "/home/tony/.emacs.d/elpa/fold-dwim-1.2" "/home/tony/.emacs.d/elpa/gandalf-theme-20130809.247" "/home/tony/.emacs.d/elpa/ghci-completion-0.1.3" "/home/tony/.emacs.d/elpa/git-gutter-0.42" "/home/tony/.emacs.d/elpa/google-contacts-20140530.233/" "/home/tony/.emacs.d/elpa/google-this-20150522.240/" "/home/tony/.emacs.d/elpa/goto-last-change-1.2" "/home/tony/.emacs.d/elpa/graphviz-dot-mode-0.3.7" "/home/tony/.emacs.d/elpa/groovy-mode-20131129" "/home/tony/.emacs.d/elpa/guide-key-20140219.531" "/home/tony/.emacs.d/elpa/haskell-mode-13.7" "/home/tony/.emacs.d/elpa/highlight-20150405.2145/" "/home/tony/.emacs.d/elpa/ht-20140122.1555/" "/home/tony/.emacs.d/elpa/htmlize-1.39" "/home/tony/.emacs.d/elpa/iedit-20150415.1804/" "/home/tony/.emacs.d/elpa/iy-go-to-char-20130901.729" "/home/tony/.emacs.d/elpa/jabber-0.8.90" "/home/tony/.emacs.d/elpa/kv-0.0.19" "/home/tony/.emacs.d/elpa/list-utils-20140508.1341/" "/home/tony/.emacs.d/elpa/magit-20150525.1145/" "/home/tony/.emacs.d/elpa/git-rebase-mode-20150122.1114/" "/home/tony/.emacs.d/elpa/git-commit-mode-20150330.1048/" "/home/tony/.emacs.d/elpa/markdown-toc-20141215.1440/" "/home/tony/.emacs.d/elpa/markdown-mode-20150606.2129/" "/home/tony/.emacs.d/elpa/math-symbol-lists-20141126.1508/" "/home/tony/.emacs.d/elpa/midje-mode-0.1.2" "/home/tony/.emacs.d/elpa/move-text-1.0" "/home/tony/.emacs.d/elpa/multi-term-0.8.8" "/home/tony/.emacs.d/elpa/multiple-cursors-1.3.0" "/home/tony/.emacs.d/elpa/names-20150125.552/" "/home/tony/.emacs.d/elpa/nix-mode-20140917.435/" "/home/tony/.emacs.d/elpa/noflet-0.0.11" "/home/tony/.emacs.d/elpa/nrepl-ritz-0.6.0" "/home/tony/.emacs.d/elpa/nrepl-0.2.0" "/home/tony/.emacs.d/elpa/clojure-mode-2.1.1" "/home/tony/.emacs.d/elpa/oauth2-0.10/" "/home/tony/.emacs.d/elpa/offlineimap-20130331.741/" "/home/tony/.emacs.d/elpa/org2blog-20130707.323" "/home/tony/.emacs.d/elpa/metaweblog-20130707.431" "/home/tony/.emacs.d/elpa/org-20140224" "/home/tony/.emacs.d/elpa/package-store-0.3" "/home/tony/.emacs.d/elpa/page-break-lines-0.9" "/home/tony/.emacs.d/elpa/paredit-20150217.713/" "/home/tony/.emacs.d/elpa/php-mode-1.5.0" "/home/tony/.emacs.d/elpa/popup-0.5" "/home/tony/.emacs.d/elpa/popwin-20130329.435" "/home/tony/.emacs.d/elpa/projectile-0.10.0" "/home/tony/.emacs.d/elpa/pkg-info-0.4" "/home/tony/.emacs.d/elpa/epl-0.5" "/home/tony/.emacs.d/elpa/dash-2.5.0" "/home/tony/.emacs.d/elpa/puppet-mode-0.2" "/home/tony/.emacs.d/elpa/redshank-20120510.1230/" "/home/tony/.emacs.d/elpa/repl-toggle-20140501.531/" "/home/tony/.emacs.d/elpa/fullframe-20140619.305/" "/home/tony/.emacs.d/elpa/request-0.2.0" "/home/tony/.emacs.d/elpa/restclient-20150513.131/" "/home/tony/.emacs.d/elpa/s-1.9.0" "/home/tony/.emacs.d/elpa/scala-mode2-20131115.2347" "/home/tony/.emacs.d/elpa/slime-repl-20100404" "/home/tony/.emacs.d/elpa/slime-20100404.1" "/home/tony/.emacs.d/elpa/smart-mode-line-20150426.910/" "/home/tony/.emacs.d/elpa/rich-minority-20150305.516/" "/home/tony/.emacs.d/elpa/smartscan-20131230.739" "/home/tony/.emacs.d/elpa/solarized-theme-20140227.1009" "/home/tony/.emacs.d/elpa/stumpwm-mode-20111113.431" "/home/tony/.emacs.d/elpa/switch-window-20150114.215/" "/home/tony/.emacs.d/elpa/toc-org-20150421.438/" "/home/tony/.emacs.d/elpa/tuareg-2.0.8" "/home/tony/.emacs.d/elpa/caml-3.12.0.1" "/home/tony/.emacs.d/elpa/twittering-mode-2.0.0" "/home/tony/.emacs.d/elpa/w3m-20150601.1727/" "/home/tony/.emacs.d/elpa/web-0.4.1" "/home/tony/.emacs.d/elpa/xml-rpc-1.6.8" "/home/tony/.emacs.d/elpa/zenburn-theme-20150512.136/" "/nix/store/pn3j6m7smaswwigmm7194cp1wfgc0glr-emacs-24.5/share/emacs/24.5/site-lisp" "/nix/store/pn3j6m7smaswwigmm7194cp1wfgc0glr-emacs-24.5/share/emacs/site-lisp" "/nix/store/pn3j6m7smaswwigmm7194cp1wfgc0glr-emacs-24.5/share/emacs/24.5/lisp" "/nix/store/pn3j6m7smaswwigmm7194cp1wfgc0glr-emacs-24.5/share/emacs/24.5/lisp/vc" "/nix/store/pn3j6m7smaswwigmm7194cp1wfgc0glr-emacs-24.5/share/emacs/24.5/lisp/url" "/nix/store/pn3j6m7smaswwigmm7194cp1wfgc0glr-emacs-24.5/share/emacs/24.5/lisp/textmodes" "/nix/store/pn3j6m7smaswwigmm7194cp1wfgc0glr-emacs-24.5/share/emacs/24.5/lisp/progmodes" "/nix/store/pn3j6m7smaswwigmm7194cp1wfgc0glr-emacs-24.5/share/emacs/24.5/lisp/play" "/nix/store/pn3j6m7smaswwigmm7194cp1wfgc0glr-emacs-24.5/share/emacs/24.5/lisp/org" "/nix/store/pn3j6m7smaswwigmm7194cp1wfgc0glr-emacs-24.5/share/emacs/24.5/lisp/nxml" "/nix/store/pn3j6m7smaswwigmm7194cp1wfgc0glr-emacs-24.5/share/emacs/24.5/lisp/net" "/nix/store/pn3j6m7smaswwigmm7194cp1wfgc0glr-emacs-24.5/share/emacs/24.5/lisp/mh-e" "/nix/store/pn3j6m7smaswwigmm7194cp1wfgc0glr-emacs-24.5/share/emacs/24.5/lisp/mail" "/nix/store/pn3j6m7smaswwigmm7194cp1wfgc0glr-emacs-24.5/share/emacs/24.5/lisp/leim" "/nix/store/pn3j6m7smaswwigmm7194cp1wfgc0glr-emacs-24.5/share/emacs/24.5/lisp/language" "/nix/store/pn3j6m7smaswwigmm7194cp1wfgc0glr-emacs-24.5/share/emacs/24.5/lisp/international" "/nix/store/pn3j6m7smaswwigmm7194cp1wfgc0glr-emacs-24.5/share/emacs/24.5/lisp/gnus" "/nix/store/pn3j6m7smaswwigmm7194cp1wfgc0glr-emacs-24.5/share/emacs/24.5/lisp/eshell" "/nix/store/pn3j6m7smaswwigmm7194cp1wfgc0glr-emacs-24.5/share/emacs/24.5/lisp/erc" "/nix/store/pn3j6m7smaswwigmm7194cp1wfgc0glr-emacs-24.5/share/emacs/24.5/lisp/emulation" "/nix/store/pn3j6m7smaswwigmm7194cp1wfgc0glr-emacs-24.5/share/emacs/24.5/lisp/emacs-parallel" "/nix/store/pn3j6m7smaswwigmm7194cp1wfgc0glr-emacs-24.5/share/emacs/24.5/lisp/emacs-lisp" "/nix/store/pn3j6m7smaswwigmm7194cp1wfgc0glr-emacs-24.5/share/emacs/24.5/lisp/cedet" "/nix/store/pn3j6m7smaswwigmm7194cp1wfgc0glr-emacs-24.5/share/emacs/24.5/lisp/calendar" "/nix/store/pn3j6m7smaswwigmm7194cp1wfgc0glr-emacs-24.5/share/emacs/24.5/lisp/calc" "/nix/store/pn3j6m7smaswwigmm7194cp1wfgc0glr-emacs-24.5/share/emacs/24.5/lisp/obsolete" "/home/tony/.emacs-live-packs/blog-pack" "/home/tony/.emacs-live-packs/browser-pack" "/home/tony/.emacs-live-packs/buffer-pack" "/home/tony/.emacs-live-packs/caml-pack" "/home/tony/.emacs-live-packs/caml-pack/lib" "/home/tony/.emacs-live-packs/chat-pack" "/home/tony/.emacs-live-packs/chrome-pack" "/home/tony/.emacs-live-packs/chrome-pack/lib" "/home/tony/.emacs-live-packs/clojure-pack" "/home/tony/.emacs-live-packs/clojurescript-pack" "/home/tony/.emacs-live-packs/clojurescript-pack/lib" "/home/tony/.emacs-live-packs/ctags-pack" "/home/tony/.emacs-live-packs/el-get-pack" "/home/tony/.emacs-live-packs/el-get-pack/lib" "/home/tony/.emacs-live-packs/elisp-pack" "/home/tony/.emacs-live-packs/git-pack" "/home/tony/.emacs-live-packs/groovy-pack" "/home/tony/.emacs-live-packs/haskell-pack" "/home/tony/.emacs-live-packs/install-packages-pack" "/home/tony/.emacs-live-packs/lisp-pack" "/home/tony/.emacs-live-packs/macro-pack" "/home/tony/.emacs-live-packs/mail-pack" "/home/tony/.emacs-live-packs/modeline-pack" "/home/tony/.emacs-live-packs/nrepl-pack" "/home/tony/.emacs-live-packs/nrepl-pack/config" "/home/tony/.emacs-live-packs/nrepl-pack/lib" "/home/tony/.emacs-live-packs/orgmode-pack" "/home/tony/.emacs-live-packs/php-pack" "/home/tony/.emacs-live-packs/prelude-live-pack" "/home/tony/.emacs-live-packs/prelude-live-pack/config" "/home/tony/.emacs-live-packs/prelude-live-pack/lib" "/home/tony/.emacs-live-packs/pres-pack" "/home/tony/.emacs-live-packs/pres-pack/resources" "/home/tony/.emacs-live-packs/pres-pack/resources/reveal.js-2.6.1" "/home/tony/.emacs-live-packs/pres-pack/resources/reveal.js-2.6.1/css" "/home/tony/.emacs-live-packs/pres-pack/resources/reveal.js-2.6.1/css/print" "/home/tony/.emacs-live-packs/pres-pack/resources/reveal.js-2.6.1/css/theme" "/home/tony/.emacs-live-packs/pres-pack/resources/reveal.js-2.6.1/css/theme/source" "/home/tony/.emacs-live-packs/pres-pack/resources/reveal.js-2.6.1/css/theme/template" "/home/tony/.emacs-live-packs/pres-pack/resources/reveal.js-2.6.1/js" "/home/tony/.emacs-live-packs/pres-pack/resources/reveal.js-2.6.1/lib" "/home/tony/.emacs-live-packs/pres-pack/resources/reveal.js-2.6.1/lib/css" "/home/tony/.emacs-live-packs/pres-pack/resources/reveal.js-2.6.1/lib/font" "/home/tony/.emacs-live-packs/pres-pack/resources/reveal.js-2.6.1/lib/js" "/home/tony/.emacs-live-packs/pres-pack/resources/reveal.js-2.6.1/plugin" "/home/tony/.emacs-live-packs/pres-pack/resources/reveal.js-2.6.1/plugin/highlight" "/home/tony/.emacs-live-packs/pres-pack/resources/reveal.js-2.6.1/plugin/leap" "/home/tony/.emacs-live-packs/pres-pack/resources/reveal.js-2.6.1/plugin/markdown" "/home/tony/.emacs-live-packs/pres-pack/resources/reveal.js-2.6.1/plugin/math" "/home/tony/.emacs-live-packs/pres-pack/resources/reveal.js-2.6.1/plugin/multiplex" "/home/tony/.emacs-live-packs/pres-pack/resources/reveal.js-2.6.1/plugin/notes" "/home/tony/.emacs-live-packs/pres-pack/resources/reveal.js-2.6.1/plugin/notes-server" "/home/tony/.emacs-live-packs/pres-pack/resources/reveal.js-2.6.1/plugin/postmessage" "/home/tony/.emacs-live-packs/pres-pack/resources/reveal.js-2.6.1/plugin/print-pdf" "/home/tony/.emacs-live-packs/pres-pack/resources/reveal.js-2.6.1/plugin/remotes" "/home/tony/.emacs-live-packs/pres-pack/resources/reveal.js-2.6.1/plugin/search" "/home/tony/.emacs-live-packs/pres-pack/resources/reveal.js-2.6.1/plugin/zoom-js" "/home/tony/.emacs-live-packs/pres-pack/resources/reveal.js-2.6.1/test" "/home/tony/.emacs-live-packs/pres-pack/resources/reveal.js-2.6.1/test/examples" "/home/tony/.emacs-live-packs/pres-pack/resources/reveal.js-2.6.1/test/examples/assets" "/home/tony/.emacs-live-packs/puppet-pack" "/home/tony/.emacs-live-packs/scala-pack" "/home/tony/.emacs-live-packs/scratch-pack" "/home/tony/.emacs-live-packs/shell-pack" "/home/tony/.emacs-live-packs/stumpwm-pack" "/home/tony/.emacs-live-packs/theme-pack" "/home/tony/.emacs-live-packs/twitter-pack")
```

And the folder your emacs-live install returns is not referenced in my actual load-path on my side.

(There is the `.emacs.d/packs/stable/bindings-pack/lib` but this one does not contain any info.el.
So no trouble here.)

Cheers,

**Comment by neverfox** [comment]
So everything is working for me when I tried it on my work computer. Before wasting any more of your time, I'll try to sort it out on my other one.

There is one thing though. The commits for mail-pack and prelude-live-pack seem to be wrong as the clone command cannot find them.

**Comment by ardumont** [comment]
> So everything is working for me when I tried it on my work computer. Before wasting any more of your time, I'll try to sort it out on my other one.

Thanks!

> There is one thing though. The commits for mail-pack and prelude-live-pack seem to be wrong as the clone command cannot find them.

I must have forgotten to push from one of my computers.
I'll see to that.

Thanks for the update.

Cheers,
